services:
  dsh-sandbox:
    extends:
      file: docker-compose.base.yaml
      service: dsh-sandbox
    build:
      args:
        - BASE_IMAGE=ubuntu:24.04
        - SOURCE_FILE=ubuntu-ports.sources
        # - HTTPS_PROXY=http://172.17.0.1:7070
    env_file:
      # - proxy.env
      - dsh.env