services:
  dsh-sandbox:
    extends:
      file: ../docker-compose.base.yaml
      service: dsh-sandbox
    build:
      args:
        - BASE_IMAGE=ubuntu:24.04
        - SOURCE_FILE=ubuntu.sources
        - HTTPS_PROXY=http://172.17.0.1:7070
    volumes:
      - /share/public/models:/models
    environment:
      - HF_HOME=/models/huggingface
      - MODELSCOPE_CACHE=/models/modelscope
      - MS_CACHE_HOME=/models/modelscope
    env_file:
      - ../dsh-proxy.env

  ninfer-v100:
    container_name: ninfer-v100
    image: lesca/ninfer-v100-sm70:latest
    stop_signal: SIGINT
    environment:
      - TZ=Asia/Shanghai
      # - MODEL=/models/ninfer/qwen3_8_27b_nvfp4.ninfer
      - MODEL=/models/ninfer/qwen3_8_27b_merkyor_coder390_nvfp4.ninfer
      # - MAX_CONCURRENCY=2
      - NINFER_ARGS=--no-thinking
      # - NINFER_ARGS=--default-reasoning-effort xhigh
    volumes:
      - /share/public/models:/models:ro
    # command: /usr/sbin/sshd -D
    ports:
      - "18080:18080"
    # command: sleep infinity
    # 启用特权模式或 GPU 支持（如果你的 Dockerfile 需要 NVIDIA CUDA 支持）
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
