services:
  dsh-sandbox:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - TZ=Asia/Shanghai
        - USERNAME=ubuntu
    user: "${UID:-1000}:${GID:-1001}"
    volumes:
      - ..:/workspace:cached,slave
      - ../.dsh:/home/ubuntu/.dsh
      - ./dsh-plugins.sh:/opt/dsh-plugins.sh
      # - ../projects/dsh-docker-proxy:/opt/dsh-docker-proxy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # env_file:
    #   - proxy.env
    #   - dsh.env
    environment:
      - TZ=Asia/Shanghai
      - DEEPSEEK_API_KEY
      - DEEPSEEK_BASE_URL
    cap_add:
      - NET_ADMIN
      - NET_RAW
    ports:
      - 13080:13080
    # 启用特权模式或 GPU 支持（如果你的 Dockerfile 需要 NVIDIA CUDA 支持）
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
