services:
  dsh-sandbox:
    extends:
      file: ../docker-compose.base.yaml
      service: dsh-sandbox
    build:
      args:
        - BASE_IMAGE=nvidia/cuda:12.8.1-cudnn-devel-ubuntu24.04
        - SOURCE_FILE=ubuntu.sources
        - HTTPS_PROXY=http://172.17.0.1:7070
    env_file:
      - ../dsh-proxy.env
    # 启用特权模式或 GPU 支持（如果你的 Dockerfile 需要 NVIDIA CUDA 支持）
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
